### ISSUE TITLE
Create a Notification Factory class to support sending messages of various formats to Discord

### ISSUE THREAD

**Issue by kapilace6** [indianracingcommunity/RLIProject#199]
Apart from the [ActivityLog class](https://github.com/indianracingcommunity/RLIProject/blob/53fb58d3c4fa46ceb956aae9770b1bd79363e3de/config/activitylog.php#L4), which logs every action (non-GET) to the DB, we would also like to send notifications of certain events to a corresponding Discord channel.

Each event would have a message format(template), a discord channel, args to fill the message.
The interface (if being built) should support an option to DM a particular user on Discord.

There may be an extension of the Notification Factory to calendar / email notifications in the future. Ensure that the interface is appropriately modeled to account for other channels.

Reference:
https://dev.to/akhilarjun/factory-pattern-java-design-patterns-5h33

**Comment by kapilace6** [comment]
## Interactions with Discord
* IRC Server is integrated with a Discord Bot. This bot contains a **BOT_TOKEN**

### What are the various features of RLIProject?
- Login
    - User tried logging in without joining server
- User Profile
    - Share user's gaming ids
    - Notify that we have a new member with these roles
- Championship Standings
- All Race Results
- Race Result
- Rule book
- Our Team
- About Us
- League Signups
    - New signup with link
    - Signups have been opened / closed (if done by coordinator through website)
    - Signup edit (if after a while)
- Allot Drivers
    - New driver alloted
- Result Parsing (ACC & AC)
- Result Upload
    - Store results backup
- Create Race Reports
    - A new report was created
- View / Edit Reports
    - Reports were edited
- Counter-report
    - A counter report was created
- Publish Stewards Verdicts
    - Verdicts were published
    - Correction was made

### What are the various tables in ircproject Database?
- Circuits
- Constructors
- Drivers
    - Updating alias
- Points
- Races 
    - When is a race scheduled? Provide its race details .(Bot Command)
    - A race was created by a coordinator, with its scheduled date & time
    - Stream link was added to the race. (Why is this notification needed?)
- Reports
    - A report was created. Post in season's reporting channel
    - Edit / Delete the reported message
    - Counter report was created to a report.
    - Verdicts were published
    - Verdict correction was made
    - Quali / Race bans to be served
- Results
    - Race result was uploaded.
    - Race results were updated via penalties. (Redundant)
- Roles
- Seasons
    - Reporting window is closed.
- Series
    - New member in server with these roles (Redundant)
- Signups
    - New league signup with link
    - Signup modified (if not edited in a while)
    - Partial signup?
- Users
    - New member in server with roles and user profile link

### Other use cases
- Any changes made to the DB by an IRC team through the website / bot.
- Notify admins of server exceptions
- Notify admins of host health issue & server status

**Comment by kapilace6** [comment]
### APIs to integrate
* [Create message](https://discord.com/developers/docs/resources/channel#create-message)
* [Message object](https://discord.com/developers/docs/resources/channel#message-object)
* [Edit message](https://discord.com/developers/docs/resources/channel#edit-message)
* [Delete message](https://discord.com/developers/docs/resources/channel#delete-message)
* [Start thread from message](https://discord.com/developers/docs/resources/channel#start-thread-from-message)
* [Add thread member](https://discord.com/developers/docs/resources/channel#add-thread-member)

### References
* [Setting up discord as a log reporter](https://panjeh.medium.com/send-laravel-6-log-to-slack-notification-573a6d95a14e)
* [Spatie Laravel discord alerts](https://github.com/spatie/laravel-discord-alerts)
* [Laravel queues](https://laravel.com/docs/6.x/queues#creating-jobs)
* [Laravel discord notification channel gist](https://gist.github.com/Cannonb4ll/a1e9fa021ab940c9ea3aca7dd5b5a011)
* [Laravel notification channels](https://github.com/laravel-notification-channels/discord/blob/master/src/Commands/SetupCommand.php)
* [Laravel jobs](https://medium.com/@sirajul.anik/how-does-laravel-jobs-get-queued-c241b04135b7)
* [Laravel notifications](https://laravel.com/docs/6.x/notifications)
* [Laravel notifications guide](https://mikey.dev/posts/2021/10/18/discord-notifications-laravel.html)

### Task List
- [ ] Thread APIs
- [ ] Deal with retries
- [ ] Error handling
- [ ] Dispatch to job with arguments
- [ ] Modify deploy.sh script to notify admins with named arguments
- [ ] Testing
- [ ] (Optional) Add an option for a callback function after executing job.

**Comment by TheFreeman15** [comment]
We should also see how to maintain a channel ID mapping in our database so each module does not have to pass the discord channel ID manually and should pass a reference of that channel ID 

Also if any notification is estimitated to have high volumes of calls to discord for sending message or running any events, ratelimits have to be taken into consideration as discord will have dynamic rate limit values for each API which is returned in a response header as X-RateLimit-Limit: 5 

Refer: [Discord Rate Limits](https://discord.com/developers/docs/topics/rate-limits)

**Comment by kapilace6** [comment]
Why is there a need for channel ID mapping? Can you provide any cons to the channel IDs being saved and retrieved from a model directly?

As for rate limits, the HTTP client we are using will take care of 429 and 5xx responses from discord, through retries. We should log every one of these errors, such that we can analyze any bottlenecks in the future.
